spring:
  application:
    name: DormitoryManagement

  datasource:
    url: jdbc:mysql://localhost:3306/ql_kytucxa
    username: root
    password: 1234567
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
